import { useMemo } from "react";
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
} from "~/components/ui/alert-dialog";
import type { ConfigEditPreview } from "~/lib/services/configs";
import type { ClassifiedEdit } from "~/lib/nginx/reverse/classify";

export interface ApplyDialogProps {
  open: boolean;
  preview: ConfigEditPreview | null; // null while the preview request is in flight
  generatedWarning: boolean; // Task 7 sets this
  onApply: () => void;
  onCancel: () => void;
  onJumpToLine: (line: number) => void; // used by refusal rows
}

type LocationRemovedEdit = Extract<ClassifiedEdit, { kind: "location-removed" }>;
type LocationAddedEdit = Extract<ClassifiedEdit, { kind: "location-added" }>;

const RECOGNISED_KINDS = new Set(["field", "location-field"]);
const RAW_KINDS = new Set(["server-advanced", "location-advanced", "prelude"]);

function groupEdits(edits: ClassifiedEdit[]) {
  const recognised: ClassifiedEdit[] = [];
  const raw: ClassifiedEdit[] = [];
  const removed: LocationRemovedEdit[] = [];
  const added: LocationAddedEdit[] = [];
  for (const edit of edits) {
    if (RECOGNISED_KINDS.has(edit.kind)) recognised.push(edit);
    else if (RAW_KINDS.has(edit.kind)) raw.push(edit);
    else if (edit.kind === "location-removed") removed.push(edit);
    else if (edit.kind === "location-added") added.push(edit);
  }
  return { recognised, raw, removed, added };
}

/**
 * The confirmation dialog every accepted config-file edit goes through
 * before anything is written — save is never silent. If the classifier
 * refused any part of the edit, only the refusal list is shown (with an
 * exact line number per refusal) and there is no apply path at all.
 */
export function ApplyDialog({
  open,
  preview,
  generatedWarning,
  onApply,
  onCancel,
  onJumpToLine,
}: ApplyDialogProps) {
  const groups = useMemo(() => (preview ? groupEdits(preview.edits) : null), [preview]);
  const refusals = preview?.refusals ?? [];
  const hasRefusals = refusals.length > 0;
  const hasAnyEdits =
    !!groups &&
    (groups.recognised.length > 0 ||
      groups.raw.length > 0 ||
      groups.removed.length > 0 ||
      groups.added.length > 0);

  return (
    <AlertDialog
      open={open}
      onOpenChange={(next) => {
        if (!next) onCancel();
      }}
    >
      <AlertDialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <AlertDialogHeader>
          <AlertDialogTitle>
            {hasRefusals ? "Can't apply this edit" : "Apply changes to the host model?"}
          </AlertDialogTitle>
          <AlertDialogDescription>
            {preview === null
              ? "Classifying your changes against the host model…"
              : hasRefusals
                ? "These changes can't be mapped back to the host model. Fix them in the editor, then save again."
                : "This is what Nginx Manager understood from your edit. Applying regenerates the file from the host model, so the text you see afterward is canonical."}
          </AlertDialogDescription>
        </AlertDialogHeader>

        {generatedWarning && (
          <div className="rounded-md border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-sm text-amber-600 dark:text-amber-400">
            This file is generated by Nginx Manager. Your changes will be overwritten the next
            time any host is created, toggled or deleted.
          </div>
        )}

        {preview === null ? (
          <div className="py-6 text-center text-sm text-muted-foreground">Loading…</div>
        ) : hasRefusals ? (
          <ul className="space-y-1 text-sm">
            {refusals.map((refusal, i) => (
              <li key={i}>
                <button
                  type="button"
                  onClick={() => onJumpToLine(refusal.line)}
                  className="text-left text-destructive underline-offset-2 hover:underline"
                >
                  line {refusal.line}: {refusal.reason}
                </button>
              </li>
            ))}
          </ul>
        ) : (
          <div className="space-y-4 text-sm">
            {groups!.recognised.length > 0 && (
              <div>
                <h4 className="mb-1 font-medium text-foreground">Recognised</h4>
                <ul className="list-disc space-y-0.5 pl-5 text-muted-foreground">
                  {groups!.recognised.map((edit, i) => (
                    <li key={i}>{edit.label}</li>
                  ))}
                </ul>
              </div>
            )}

            {groups!.raw.length > 0 && (
              <div>
                <h4 className="mb-1 font-medium text-foreground">Kept as raw</h4>
                <ul className="list-disc space-y-0.5 pl-5 text-muted-foreground">
                  {groups!.raw.map((edit, i) => (
                    <li key={i}>{edit.label}</li>
                  ))}
                </ul>
              </div>
            )}

            {groups!.removed.length > 0 && (
              <div>
                <h4 className="mb-1 font-medium text-foreground">Removed</h4>
                <ul className="list-disc space-y-1 pl-5 text-muted-foreground">
                  {groups!.removed.map((edit, i) => (
                    <li key={i}>
                      {edit.label}
                      {edit.losing.length > 0 && (
                        <ul className="list-disc space-y-0.5 pl-5">
                          {edit.losing.map((item, j) => (
                            <li key={j}>{item}</li>
                          ))}
                        </ul>
                      )}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {groups!.added.length > 0 && (
              <div>
                <h4 className="mb-1 font-medium text-foreground">Added</h4>
                <ul className="list-disc space-y-0.5 pl-5 text-muted-foreground">
                  {groups!.added.map((edit, i) => (
                    <li key={i}>{edit.label}</li>
                  ))}
                </ul>
              </div>
            )}

            {!hasAnyEdits && (
              <p className="text-muted-foreground">
                No changes were detected (only formatting or comments).
              </p>
            )}
          </div>
        )}

        <AlertDialogFooter>
          {hasRefusals ? (
            <AlertDialogCancel onClick={() => onCancel()}>Close</AlertDialogCancel>
          ) : (
            <>
              <AlertDialogCancel onClick={() => onCancel()}>Cancel</AlertDialogCancel>
              <AlertDialogAction
                disabled={preview === null}
                onClick={(event) => {
                  // Stop AlertDialogAction's built-in auto-close (it's a Dialog.Close
                  // under the hood) so the dialog stays open while the write request
                  // is in flight, and can be re-rendered with refusals if it fails.
                  event.preventDefault();
                  onApply();
                }}
              >
                Apply
              </AlertDialogAction>
            </>
          )}
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
