import { type RouteConfig, route, index, layout, prefix } from "@react-router/dev/routes";

export default [
  index("./routes/home.tsx"),
  route("login", "./routes/login.tsx"),
  route("logout", "./routes/logout.tsx"),
  route("api/logs", "./routes/api/logs.tsx"),
  route("api/test-upstream", "./routes/api/test-upstream.tsx"),
  route("api/configs", "./routes/api/configs.tsx"),
  route("api/config-file", "./routes/api/config-file.tsx"),
  route("api/system-stats", "./routes/api/system-stats.tsx"),
  route("api/totp-verify", "./routes/api/totp-verify.tsx"),
  route("api/totp-setup", "./routes/api/totp-setup.tsx"),
  route("api/webauthn-challenge", "./routes/api/webauthn-challenge.tsx"),
  route("api/webauthn-verify", "./routes/api/webauthn-verify.tsx"),
  route("api/webauthn-register", "./routes/api/webauthn-register.tsx"),
  route("api/recovery-codes", "./routes/api/recovery-codes.tsx"),
  route("api/terminal-token", "./routes/api/terminal-token.tsx"),
  route("api/export", "./routes/api/export.tsx"),
  route("api/import", "./routes/api/import.tsx"),
  route("api/import-apply", "./routes/api/import-apply.tsx"),
  route("api/mcp/:secret?", "./routes/api/mcp.tsx"),
  route("api/cluster-receive", "./routes/api/cluster-receive.tsx"),
  route("api/dns", "./routes/api/dns.tsx"),
  route("api/acme-dns", "./routes/api/acme-dns.tsx"),
  route("api/user-theme", "./routes/api/user-theme.tsx"),

  layout("./routes/admin/layout.tsx", [
    ...prefix("admin", [
      index("./routes/admin/dashboard.tsx"),
      route("hosts", "./routes/admin/hosts/index.tsx"),
      route("hosts/new", "./routes/admin/hosts/new.tsx"),
      route("hosts/:id/edit", "./routes/admin/hosts/edit.tsx"),
      route("ssl", "./routes/admin/ssl.tsx"),
      route("access-lists", "./routes/admin/access-lists.tsx"),
      route("error-pages", "./routes/admin/error-pages.tsx"),
      route("default-page", "./routes/admin/default-page.tsx"),
      route("configs", "./routes/admin/configs.tsx"),
      route("templates", "./routes/admin/templates.tsx"),
      route("logs", "./routes/admin/logs.tsx"),
      route("audit-log", "./routes/admin/audit-log.tsx"),
      route("terminal", "./routes/admin/terminal.tsx"),
      route("users", "./routes/admin/users.tsx"),
      route("security", "./routes/admin/security.tsx"),
      route("settings", "./routes/admin/settings.tsx"),
      route("cluster", "./routes/admin/cluster.tsx"),
      route("dns", "./routes/admin/dns.tsx"),
      route("change-password", "./routes/admin/change-password.tsx"),
    ]),
  ]),
  route("admin/setup", "./routes/admin/setup.tsx"),
] satisfies RouteConfig;
