import { db } from "~/lib/db/connection";
import {
  hosts,
  accessLists,
  accessListClients,
  accessListAuth,
  settings,
  hostGroups,
} from "~/lib/db/schema";
import { eq } from "drizzle-orm";
import { writeFileSync, mkdirSync, readdirSync, unlinkSync, existsSync } from "fs";
import { join } from "path";
import { buildServerBlock, type HostConfig } from "./templates/server-block";
import { buildStreamBlock } from "./templates/stream";
import { buildHtpasswdContent, type AccessListWithRules } from "./templates/access";

const NGINX_CONF_DIR = process.env.NGINX_CONF_DIR || "/etc/nginx";
const DATA_NGINX_DIR = process.env.DATA_NGINX_DIR || "/data/nginx";
const HOST_CONF_DIR = join(DATA_NGINX_DIR, "conf.d");
const STREAM_CONF_DIR = join(DATA_NGINX_DIR, "stream.d");
const AUTH_DIR = join(DATA_NGINX_DIR, "auth");

/**
 * Generate all nginx configuration files from the database.
 */
export function generateAllConfigs() {
  mkdirSync(HOST_CONF_DIR, { recursive: true });
  mkdirSync(STREAM_CONF_DIR, { recursive: true });
  mkdirSync(AUTH_DIR, { recursive: true });

  // Clean old host configs
  cleanDir(HOST_CONF_DIR, "host-");
  cleanDir(STREAM_CONF_DIR, "host-");

  generateMainConfig();
  generateAdminConfig();
  generateStatusConfig();
  generateDefaultServerConfig();
  generateAccessListFiles();
  generateHostAuthFiles();

  // Load access lists for server block generation
  const accessListMap = loadAccessLists();

  const dnsResolver = db.select().from(settings).where(eq(settings.key, "dns_resolver")).get()?.value || "";
  const dnsResolverValid = db.select().from(settings).where(eq(settings.key, "dns_resolver_valid")).get()?.value || "30s";

  const allHosts = db.select().from(hosts).all();
  for (const host of allHosts) {
    if (!host.enabled) continue;
    generateHostConfig(host, accessListMap, dnsResolver, dnsResolverValid);
  }
}

/**
 * Generate config for a single host.
 */
function generateHostConfig(
  host: typeof hosts.$inferSelect,
  accessListMap: Map<number, AccessListWithRules>,
  dnsResolver: string,
  dnsResolverValid: string
) {
  const hostConfig = mapHostToConfig(host, dnsResolver, dnsResolverValid);

  // HTTP server block
  if (hostConfig.domains.length > 0 && (hostConfig.locations ?? []).length > 0) {
    const serverBlock = buildServerBlock(hostConfig, accessListMap);
    if (serverBlock) {
      writeFileSync(join(HOST_CONF_DIR, `host-${host.id}.conf`), serverBlock);
    }
  }

  // Stream blocks
  const streamPorts = host.streamPorts ?? [];
  if (streamPorts.length > 0) {
    const streamBlock = buildStreamBlock(host.id, streamPorts as any, dnsResolver, dnsResolverValid);
    if (streamBlock) {
      writeFileSync(
        join(STREAM_CONF_DIR, `host-${host.id}-stream.conf`),
        `# Stream: Host ${host.id}\n# Auto-generated by Nginx Manager.\n\n${streamBlock}`
      );
    }
  }
}

/**
 * Remove configs for a deleted host.
 */
export function removeHostConfig(id: number) {
  try { unlinkSync(join(HOST_CONF_DIR, `host-${id}.conf`)); } catch {}
  try { unlinkSync(join(STREAM_CONF_DIR, `host-${id}-stream.conf`)); } catch {}
}

/**
 * Generate the main nginx.conf.
 */
export function generateMainConfig() {
  const config = `# Auto-generated by Nginx Manager. Do not edit manually.
worker_processes auto;
worker_rlimit_nofile 65535;
error_log /data/logs/error.log warn;
pid /run/nginx.pid;

events {
    worker_connections 4096;
    multi_accept on;
    use epoll;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /data/logs/access.log main buffer=16k flush=5s;

    # Performance
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 1000;
    reset_timedout_connection on;
    types_hash_max_size 2048;
    server_names_hash_bucket_size 128;
    client_max_body_size 100m;

    # Proxy defaults
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    proxy_buffering on;
    proxy_buffer_size 4k;
    proxy_buffers 8 16k;
    proxy_busy_buffers_size 32k;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_types text/plain text/css text/xml application/json application/javascript application/xml+rss application/atom+xml image/svg+xml application/xhtml+xml font/woff2;

    # Security headers
    map $upstream_http_x_request_id $req_id {
        default $upstream_http_x_request_id;
        ""      $request_id;
    }

    include /data/nginx/conf.d/*.conf;
}

stream {
    include /data/nginx/stream.d/*.conf;
}
`;
  writeFileSync(join(NGINX_CONF_DIR, "nginx.conf"), config);
}

/**
 * Generate admin proxy config (port 81 -> web admin on 3001).
 */
function generateAdminConfig() {
  const terminalPort = process.env.TERMINAL_WS_PORT || "3002";
  const config = `# Admin panel proxy — auto-generated by Nginx Manager.
server {
    listen 81;
    listen [::]:81;

    location /terminal {
        proxy_pass http://127.0.0.1:${terminalPort};
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
`;
  writeFileSync(join(HOST_CONF_DIR, "admin.conf"), config);
}

/**
 * Generate the internal stub_status server (port 51820, localhost only)
 * polled by the dashboard via lib/system/stats.ts.
 */
function generateStatusConfig() {
  const config = `# Internal nginx status endpoint — auto-generated by Nginx Manager.
server {
    listen 127.0.0.1:51820;
    server_name _;
    access_log off;

    location /nginx_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
    }
}
`;
  writeFileSync(join(HOST_CONF_DIR, "status.conf"), config);
}

/**
 * Generate default server block (catch-all for unconfigured domains).
 */
function generateDefaultServerConfig() {
  const globalErrorDir = "/data/error-pages/global";
  const hasErrorPages = existsSync(globalErrorDir);

  const errorBlock = hasErrorPages
    ? `
    error_page 404 /_errors/404.html;
    error_page 500 /_errors/500.html;
    error_page 502 /_errors/502.html;
    error_page 503 /_errors/503.html;
    error_page 504 /_errors/504.html;

    location /_errors/ {
        alias ${globalErrorDir}/;
        internal;
    }
`
    : "";

  const config = `# Default server — catch-all for unconfigured domains.
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
${errorBlock}
    location / {
        root /data/default-page;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /.well-known/acme-challenge/ {
        alias /data/acme-challenge/;
    }
}
`;
  writeFileSync(join(HOST_CONF_DIR, "default.conf"), config);
}

/**
 * Generate htpasswd files for all access lists with auth entries.
 */
export function generateAccessListFiles() {
  mkdirSync(AUTH_DIR, { recursive: true });

  // Clean old htpasswd files
  cleanDir(AUTH_DIR, "access-list-");

  const lists = db.select().from(accessLists).all();
  for (const list of lists) {
    const auth = db
      .select()
      .from(accessListAuth)
      .where(eq(accessListAuth.accessListId, list.id))
      .all();

    if (auth.length > 0) {
      const content = buildHtpasswdContent(auth);
      writeFileSync(join(AUTH_DIR, `access-list-${list.id}.htpasswd`), content);
    }
  }
}

/**
 * Generate htpasswd files for hosts with inline basic auth.
 */
function generateHostAuthFiles() {
  // Clean old host auth files
  cleanDir(AUTH_DIR, "host-");

  const allHosts = db.select().from(hosts).all();
  for (const host of allHosts) {
    if (!host.enabled) continue;

    const basicAuth = (host as any).basicAuth;

    // Host-level htpasswd
    if (basicAuth?.enabled && basicAuth.users?.length > 0) {
      const content = buildHtpasswdContent(basicAuth.users);
      writeFileSync(join(AUTH_DIR, `host-${host.id}.htpasswd`), content);
    }

    // Per-location htpasswd
    const locations = (host.locations ?? []) as any[];
    for (let i = 0; i < locations.length; i++) {
      const loc = locations[i];
      if (loc.basicAuth?.enabled && loc.basicAuth.users?.length > 0) {
        const content = buildHtpasswdContent(loc.basicAuth.users);
        writeFileSync(join(AUTH_DIR, `host-${host.id}-loc-${i}.htpasswd`), content);
      }
    }
  }
}

// ─── Helpers ─────────────────────────────────────────────

function mapHostToConfig(host: typeof hosts.$inferSelect, dnsResolver: string, dnsResolverValid: string): HostConfig {
  // Determine error pages directory
  let errorPagesDir: string | null = null;
  const hostErrorDir = `/data/error-pages/host-${host.id}`;
  const groupErrorDir = host.groupId
    ? `/data/error-pages/group-${host.groupId}`
    : null;
  const globalErrorDir = "/data/error-pages/global";

  if (existsSync(hostErrorDir)) {
    errorPagesDir = hostErrorDir;
  } else if (groupErrorDir && existsSync(groupErrorDir)) {
    errorPagesDir = groupErrorDir;
  } else if (existsSync(globalErrorDir)) {
    errorPagesDir = globalErrorDir;
  }

  return {
    id: host.id,
    groupId: host.groupId,
    domains: host.domains ?? [],
    enabled: host.enabled,
    sslType: host.sslType,
    sslForceHttps: host.sslForceHttps,
    sslCertPath: host.sslCertPath,
    sslKeyPath: host.sslKeyPath,
    hsts: host.hsts,
    http2: host.http2,
    compression: host.compression,
    redirectWww: host.redirectWww,
    clientMaxBodySize: host.clientMaxBodySize,
    locations: (host.locations ?? []).map((loc: any) => ({
      path: loc.path ?? "/",
      matchType: loc.matchType ?? "prefix",
      type: loc.type ?? "proxy",
      upstreams: loc.upstreams ?? [],
      balanceMethod: loc.balanceMethod ?? "round_robin",
      staticDir: loc.staticDir ?? "",
      cacheExpires: loc.cacheExpires ?? "",
      forwardScheme: loc.forwardScheme ?? "http",
      forwardDomain: loc.forwardDomain ?? "",
      forwardPath: loc.forwardPath ?? "/",
      preservePath: loc.preservePath ?? true,
      statusCode: loc.statusCode ?? 301,
      headers: loc.headers ?? {},
      accessListId: loc.accessListId ?? null,
      basicAuth: loc.basicAuth ?? null,
    })),
    advancedNginx: host.advancedNginx,
    webhookUrl: host.webhookUrl,
    errorPagesDir,
    basicAuth: (host as any).basicAuth ?? null,
    dnsResolver: dnsResolver || null,
    dnsResolverValid: dnsResolverValid || null,
  };
}

function loadAccessLists(): Map<number, AccessListWithRules> {
  const map = new Map<number, AccessListWithRules>();
  const lists = db.select().from(accessLists).all();

  for (const list of lists) {
    const clients = db
      .select()
      .from(accessListClients)
      .where(eq(accessListClients.accessListId, list.id))
      .all();
    const auth = db
      .select()
      .from(accessListAuth)
      .where(eq(accessListAuth.accessListId, list.id))
      .all();

    map.set(list.id, {
      id: list.id,
      name: list.name,
      satisfy: list.satisfy,
      clients: clients.map((c) => ({
        address: c.address,
        directive: c.directive,
      })),
      auth: auth.map((a) => ({ username: a.username, password: a.password })),
    });
  }

  return map;
}

function cleanDir(dir: string, prefix: string) {
  try {
    const files = readdirSync(dir);
    for (const f of files) {
      if (f.startsWith(prefix)) {
        unlinkSync(join(dir, f));
      }
    }
  } catch {}
}
